### ISSUE TITLE
Test of an issue

### ISSUE THREAD

**Issue by eshira** [MOARbots/apriltags#1]
I need to see if I can use issues to manage what I currently call the "task list"

**Comment by ArchimedesPi** [comment]
Check out https://waffle.io/ for this kind of thing, it works really well.

**Comment by eshira** [comment]
I'll check it out. Thanks!

**Comment by eshira** [comment]
I created a board for https://waffle.io/moarbots/wixel-sdk and https://waffle.io/moarbots/apriltags. It would be great to create an organization wide board but that isn't fully supported yet, unless a dummy repo is created (MOARbots/MOARbots, for example), a board is created for it, and then multiple repos are added to this board.
