### ISSUE TITLE
Remove `_t` suffix from typedefs in capriltag

### ISSUE THREAD

**Issue by erinzm** [MOARbots/apriltags#8]
On POSIX-compliant systems, the **`_t`** suffix on struct typedefs is reserved for system types. I need to refactor the entire library to remove `_t` suffixes on struct typedefs.

**Comment by ArchimedesPi** [comment]
Since I've moved this repo to [MOARbots/apriltags-c](https://github.com/MOARbots/apriltags-c), this issue is no longer relevant.
